### ISSUE TITLE
MAkerBoard buyers guide

### ISSUE THREAD

**Issue by MaderDash** [MaderDash/arduino-discord-wiki#30]
### Discussed in https://github.com/MaderDash/arduino-discord-wiki/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **MaderDash** November  5, 2022</sup>
There are some errors in both of these files, so I removed them from the wiki, until we can do a review check to resolve the issue.
They are on a seperate branch and after the corrections have been made, they will be merged into the dev branch.

@scrapboy13 @wa1tnr 

Files [maker]([makerboards.md](https://github.com/MaderDash/arduino-discord-wiki/blob/maker-branch/makerboards.md)
and
[guide]([arduinobuyersguide.md](https://github.com/MaderDash/arduino-discord-wiki/blob/maker-branch/arduinobuyersguide.md)

Both need to be gone through board by board, it looks like some of the stats are just out of order, but we need to proof check them at this point.

</div>

**Comment by wa1tnr** [comment]
Just saw this (7:30 pm NYC time).

I got a lot on my plate this week.

**Comment by scrapboy13** [comment]
my pull request shoud fix above isues

**Comment by MaderDash** [comment]
all done
